# Generated by Django 4.2.7 on 2023-12-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billswift',
            name='field_name',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
