# Generated by Django 4.2.7 on 2023-12-03 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_billswift_field_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billswift',
            name='field_name',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
