# Generated by Django 4.2.7 on 2023-12-03 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_billswift_field_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billswift',
            old_name='field_name',
            new_name='date_time',
        ),
    ]
