# Generated by Django 4.2.7 on 2024-04-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0004_rename_field_name_billswift_date_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_upload", models.DateField()),
                ("email", models.EmailField(max_length=254)),
                ("date_on_bill", models.DateField()),
                ("title", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("status", models.CharField(max_length=50)),
                (
                    "view_bill",
                    models.FileField(
                        upload_to="D:\\BillSwift_p1\\media\\media\\Billswift"
                    ),
                ),
            ],
        ),
    ]
