# Generated by Django 4.2.7 on 2024-04-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0005_billdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billdata",
            name="view_bill",
            field=models.ImageField(upload_to="media/Billswift"),
        ),
    ]
