# Generated by Django 4.2.7 on 2024-04-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0006_alter_billdata_view_bill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billdata",
            name="date_of_upload",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="billdata",
            name="date_on_bill",
            field=models.CharField(max_length=255),
        ),
    ]
